name: Build and release plugin

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: Build checksum
      run: |
        sha512sum ./target/teamcity_finish_build_hook_plugin.zip | cut -f1 -d" " >> ./target/teamcity_finish_build_hook_plugin.zip.sha512
    - name: Set version
      run: |
        git pull --tags
        export snapshot_version="$(mvn -B org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version 2> /dev/null | grep -Ev '(^\[|Download\w+:)')"
        export version="${snapshot_version%-SNAPSHOT}"
        dev_version="${version}-dev.$(( $(while read v; do echo "${v##*.}"; done<<<"$(git tag | grep "${version}-dev.")" | sort -h | tail -n1) + 1 ))"

        echo "version=${dev_version}" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: true
    - name: Upload Release Asset Zip
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/teamcity_finish_build_hook_plugin.zip
        asset_name: teamcity-finish-build-hook-plugin.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Hash
      id: upload-release-asset-checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/teamcity_finish_build_hook_plugin.zip.sha512
        asset_name: teamcity-finish-build-hook-plugin.zip.sha512
        asset_content_type: text/plain